name: Secret Scan (2MS)

on: [push,pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifacts directory
        run: |
          mkdir -p artifacts

      - name: Run 2MS and create readable report
        run: |
          docker run --rm \
            -v "$PWD":/repo \
            checkmarx/2ms \
            git /repo \
            --stdout-format yaml \
            --ignore-on-exit results \
            > artifacts/2ms-report.txt

      - name: Check report
        if: always()
        run: |
          echo "======================================"
          echo "2MS REPORT"
          echo "======================================"

          ls -lah artifacts/

          echo ""
          cat artifacts/2ms-report.txt

      - name: Upload 2MS report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 2ms-security-report
          path: artifacts/2ms-report.txt
          if-no-files-found: error
          retention-days: 30